# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pennies}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jiri Zajpt"]
  s.date = %q{2010-11-18}
  s.description = %q{Pennies handles your money and currency needs. Support Mongoid and MongoMapper.}
  s.email = %q{jzajpt@blueberry.cz}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/pennies.rb",
    "lib/pennies/currency.rb",
    "lib/pennies/exchange_bank.rb",
    "lib/pennies/money.rb",
    "lib/pennies/mongo/currency_extensions.rb",
    "lib/pennies/mongo/money_extensions.rb",
    "lib/pennies/validators/currency_code_validator.rb"
  ]
  s.homepage = %q{http://github.com/jzajpt/pennies}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Money and Currency handling library.}
  s.test_files = [
    "spec/pennies/currency_spec.rb",
    "spec/pennies/exchange_bank_spec.rb",
    "spec/pennies/money_spec.rb",
    "spec/pennies/pennies_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.2"])
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.0.2"])
      s.add_runtime_dependency(%q<mongoid>, ["~> 2.0.0.beta.20"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.0.2"])
      s.add_dependency(%q<activemodel>, ["~> 3.0.2"])
      s.add_dependency(%q<mongoid>, ["~> 2.0.0.beta.20"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.0.2"])
    s.add_dependency(%q<activemodel>, ["~> 3.0.2"])
    s.add_dependency(%q<mongoid>, ["~> 2.0.0.beta.20"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
  end
end

